### ISSUE TITLE
#BUG 重复输入导致他无法正常处理

### ISSUE THREAD

**Issue by xuebkgithub** [johanazhu/honghongai#1]
只要吵几句话.在重复状态下.就会出现.

![CleanShot 2024-01-25 at 16 53 31](https://github.com/johanazhu/honghongai/assets/41730586/457279a2-d863-4ed7-a425-e5a10de295a6)

**Comment by johanazhu** [comment]
嗯嗯，说明 Gemini 不够智能

**Comment by xuebkgithub** [comment]
我觉得.可以在最初初始化的时候.增加.对于重复内容的判断.多次重复就减分

**Comment by johanazhu** [comment]
> 我觉得.可以在最初初始化的时候.增加.对于重复内容的判断.多次重复就减分

好的，已经修改

**Comment by xbpk3t** [comment]
hhhhh 这个bug太逗了
