### ISSUE TITLE
运行问题

### ISSUE THREAD

**Issue by SauerkrautFFish** [johanazhu/honghongai#2]
我看整个项目几乎都是ts文件，没有找到html文件，能给小白解惑下嘛？我不知道入口在哪里

**Comment by johanazhu** [comment]
这是基于 [nextjs](https://nextjs.org/) 做的网站。简单来说就是基于框架来做的网站，不是传统的 html+css+js

**Comment by SauerkrautFFish** [comment]
那我要怎么运行呀，请指教~~~，我实在不懂QAQ，打开哪一个文件呀
