### ISSUE TITLE
fetch failed from googleapi

### ISSUE THREAD

**Issue by dwgeneral** [johanazhu/honghongai#4]
<img width="811" alt="Screenshot 2024-02-02 at 21 09 18" src="https://github.com/johanazhu/honghongai/assets/8654993/2991a7aa-eead-48c8-b6e1-7e80e692f361">

I have enabled the global proxy on my Mac, did you got the error before?

**Comment by johanazhu** [comment]
开个代理：https://simonmy.com/posts/%E4%BD%BF%E7%94%A8netlify%E5%8F%8D%E5%90%91%E4%BB%A3%E7%90%86google-palm-api.html

**Comment by johanazhu** [comment]
> <img alt="Screenshot 2024-02-02 at 21 09 18" width="811" src="https://private-user-images.githubusercontent.com/8654993/301853498-2991a7aa-eead-48c8-b6e1-7e80e692f361.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY5MjIxMjIsIm5iZiI6MTcwNjkyMTgyMiwicGF0aCI6Ii84NjU0OTkzLzMwMTg1MzQ5OC0yOTkxYTdhYS1lZWFkLTQ4YzgtYjZlMS03ZTgwZTY5MmYzNjEucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDIwMyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAyMDNUMDA1NzAyWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZjIxYTg1ZTQzNzA4NWZkMDA1NGVmZmQ5ZmE1NDA5NTIwYTIxOGE2Y2ExNjlkOTE2ODUwNGYzM2JlZjNjNGJiOCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.tUCO30l8tUzZkEKhqFfiJhDzsq3ak7CceqdN9EC7Cyw">
> I have enabled the global proxy on my Mac, did you got the error before?

开个代理，如：https://simonmy.com/posts/%E4%BD%BF%E7%94%A8netlify%E5%8F%8D%E5%90%91%E4%BB%A3%E7%90%86google-palm-api.html
