### ISSUE TITLE
您已达今天的访问限制

### ISSUE THREAD

**Issue by suvuecoding** [johanazhu/honghongai#6]
本地启动后，会请求http://localhost:3000/api/chat，请问大佬这个地址是什么呢？我该用什么替换？

**Comment by johanazhu** [comment]
api/chat 就是你的请求接口，代码也写的很清楚了，最终会请求 startChatAndSendMessageStream，你可以在utils/OpenAIStream.ts 中找到 gemini 的请求

**Comment by suvuecoding** [comment]
好的，谢谢🙏
